# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.16.3
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - bundle-data:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: ["sh", "-c", "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload --livereload-port 35729"]

volumes:
  bundle-data:
